UTF8_HEADER = "@UTF8"
PID_HEADER = "@PID"
COLOR_WORDS_HEADER = "@ColorWords"
WINDOW_HEADER = "@Window"
FONT_HEADER = "@Font"
HIDDEN_HEADERS = [
    UTF8_HEADER,
    PID_HEADER,
    COLOR_WORDS_HEADER,
    WINDOW_HEADER,
    FONT_HEADER,
]

BEGIN_HEADER = "@Begin"
LANGUAGES_HEADER = "@Languages"
PARTICIPANTS_HEADER = "@Participants"
OPTIONS_HEADER = "@Options"
ID_HEADER = "@ID"
MEDIA_HEADER = "@Media"
END_HEADER = "@End"
INITIAL_HEADERS = [
    BEGIN_HEADER,
    LANGUAGES_HEADER,
    PARTICIPANTS_HEADER,
    OPTIONS_HEADER,
    ID_HEADER,
    MEDIA_HEADER,
    END_HEADER,
]

BIRTH_HEADER = "@Birth"
BIRTHPLACE_HEADER = "@Birthplace"
L1_HEADER = "@L1"
PARTICIPANT_SPECIFIC_HEADERS = [
    BIRTH_HEADER,
    BIRTHPLACE_HEADER,
    L1_HEADER,
]

LOCATION_HEADER = "@Location"
NUMBER_HEADER = "@Number"
RECORDING_QUALITY_HEADER = "@Recording Quality"
ROOM_LAYOUT_HEADER = "@Room Layout"
TAPE_LOCATION_HEADER = "@Tape Location"
TIME_DURATION_HEADER = "@Time Duration"
TIME_START_HEADER = "@Time Start"
TRANSCRIBER_HEADER = "@Transcriber"
TRANSCRIPTION_HEADER = "@Transcription"
TYPES_HEADER = "@Types"
VIDEOS_HEADER = "@Videos"
WARNING_HEADER = "@Warning"
CONSTANT_HEADERS = [
    LOCATION_HEADER,
    NUMBER_HEADER,
    RECORDING_QUALITY_HEADER,
    ROOM_LAYOUT_HEADER,
    TAPE_LOCATION_HEADER,
    TIME_DURATION_HEADER,
    TIME_START_HEADER,
    TRANSCRIBER_HEADER,
    TRANSCRIPTION_HEADER,
    TYPES_HEADER,
    VIDEOS_HEADER,
    WARNING_HEADER,
]

ACTIVITIES_HEADER = "@Activities"
BCK_HEADER = "@Bck"
BG_HEADER = "@Bg"
BLANK_HEADER = "@Blank"
COMMENT_HEADER = "@Comment"
DATE_HEADER = "@Date"
EG_HEADER = "@Eg"
G_HEADER = "@G"
NEW_EPISODE_HEADER = "@New Episode"
PAGE_HEADER = "@Page"
SITUATION_HEADER = "@Situation"
CHANGABLE_HEADERS = [
    ACTIVITIES_HEADER,
    BCK_HEADER,
    BG_HEADER,
    BLANK_HEADER,
    COMMENT_HEADER,
    DATE_HEADER,
    EG_HEADER,
    G_HEADER,
    NEW_EPISODE_HEADER,
    PAGE_HEADER,
    SITUATION_HEADER,
]

SEGMENT_PREFIX = "@T"

SUBJECT_ID_COL = "subject_id"
SEGMENT_ID_COL = "segment_id"
ROW_NUMBER_COL = "row_number"
SPEAKER_COL = "speaker"
LANGUAGE_COL = "lang"
SENTENCE_COL = "sentence"
SWITCH_COUNT = "switch_number"

TABLE_COLS = [
    SUBJECT_ID_COL,
    SEGMENT_ID_COL,
    ROW_NUMBER_COL,
    SPEAKER_COL,
    SENTENCE_COL,
    SWITCH_COUNT,
]
